# Generated by Django 3.1.2 on 2020-10-29 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seasons',
            new_name='Season',
        ),
    ]
