# Generated by Django 3.1.2 on 2020-10-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0003_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='image',
        ),
        migrations.AddField(
            model_name='box',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
