# Generated by Django 3.1.2 on 2020-10-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0004_auto_20201030_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
