# Generated by Django 3.1.2 on 2020-10-30 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0005_box_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Box',
            new_name='Boxes',
        ),
    ]
