# Generated by Django 3.1.2 on 2020-10-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0006_auto_20201030_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxes',
            name='fruit',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='boxes',
            name='veg',
            field=models.TextField(null=True),
        ),
    ]
