# Generated by Django 3.1.2 on 2020-10-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0007_auto_20201030_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxes',
            name='fruit',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='boxes',
            name='veg',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
