# Generated by Django 3.1.2 on 2020-10-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0008_auto_20201030_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RenameField(
            model_name='boxes',
            old_name='season',
            new_name='category',
        ),
        migrations.AddField(
            model_name='season',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='fruit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='season',
            name='month_1',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='month_2',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='month_3',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='veg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boxes',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boxes',
            name='fruit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boxes',
            name='veg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
