# Generated by Django 3.1.2 on 2020-11-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
