# Generated by Django 3.1.2 on 2020-11-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_per_box',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
