# Generated by Django 3.1.2 on 2020-11-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price_per_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_a_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
