# Generated by Django 3.1.2 on 2020-11-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_a_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
